# Generated by Django 3.2.13 on 2022-04-15 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Automation.project'),
        ),
    ]
