# Generated by Django 3.2.13 on 2022-04-17 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0002_alter_function_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Automation.project'),
        ),
    ]
