# Generated by Django 3.2.13 on 2022-05-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0003_alter_function_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.IntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='function',
            name='name',
            field=models.CharField(max_length=12),
        ),
    ]
