# Generated by Django 3.2.13 on 2022-05-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0004_auto_20220502_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDS_Content',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12, unique=True)),
                ('category', models.CharField(max_length=12, unique=True)),
                ('content', models.FileField(upload_to='SDS/')),
            ],
        ),
    ]
