# Generated by Django 3.2.13 on 2022-05-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0006_alter_sds_content_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sds_content',
            name='category',
            field=models.CharField(max_length=12),
        ),
    ]
