# Generated by Django 3.2.13 on 2022-05-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0007_alter_sds_content_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICON_Content',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(max_length=12)),
                ('content', models.FileField(upload_to='SDS/')),
            ],
        ),
    ]
