# Generated by Django 3.2.13 on 2022-05-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0008_icon_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_detail',
            name='desc',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='icon_content',
            name='content',
            field=models.FileField(upload_to='ICON/'),
        ),
    ]
